name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'   # pick 18 or 20, just be consistent
          # IMPORTANT: do NOT set "cache" here

      - name: Install dependencies
        # npm ci requires a lockfile; use install instead
        run: npm install --no-audit --no-fund

      - name: Build (Next.js)
        run: npm run build

      # Optional – won’t fail the workflow if scripts are missing
      - name: Typecheck (optional)
        run: npm run typecheck || echo "typecheck skipped"

      - name: Lint (optional)
        run: npm run lint || echo "lint skipped"
