name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'   # or '20' if you prefer; keep consistent with your project

      # No cache here because there is no lockfile yet
      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Build (Next.js)
        run: npm run build

      # Optional: only if you want these to run when present. They won't fail the workflow.
      - name: Typecheck (optional)
        run: npm run typecheck || echo "typecheck skipped"
      - name: Lint (optional)
        run: npm run lint || echo "lint skipped"
