name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Show Node & npm
        run: |
          node -v
          npm -v

      - name: Cache npm (no lockfile required)
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install deps (no lockfile)
        run: npm install --no-fund --no-audit

      - name: Build
        env:
          NEXT_TELEMETRY_DISABLED: 1
          NEXT_DISABLE_ESLINT: 1       # extra guard; also set in next.config.js below
        run: npm run build

      - name: Typecheck (optional)
        run: npm run typecheck || true

      - name: Lint (optional)
        run: npm run lint || true
