name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: 'npm'

      - name: Install dependencies (lockfile if present)
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      - name: Print Node & npm versions
        run: |
          node -v
          npm -v
          npx next --version || true

      # Runs lint if an ESLint config exists, but does NOT fail the job
      - name: Lint (non-blocking)
        if: ${{ hashFiles('.eslintrc*') != '' || hashFiles('**/.eslintrc*') != '' }}
        run: npm run lint || echo "Lint failed, continuing (non-blocking)"
        continue-on-error: true

      - name: Build
        run: npm run build
