name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # IMPORTANT: no "cache: 'npm'" here, because we don't have a lockfile yet
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install --no-audit --no-fund

      - name: Typecheck (optional)
        run: npm run typecheck
        continue-on-error: true

      - name: Lint (optional)
        run: npm run lint
        continue-on-error: true

      - name: Build (Next.js)
        run: npm run build
