name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: build-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 22.x
        uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: npm

      - name: Show Node & npm versions
        run: |
          node -v
          npm -v

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci
          else
            npm install
          fi

      # Lint is optional — won’t fail CI
      - name: Run lint (optional)
        run: npm run lint || echo "Lint failed but continuing"

      # Typecheck is optional — won’t fail CI
      - name: Run typecheck (optional)
        run: npm run typecheck || echo "Typecheck failed but continuing"

      - name: Build project
        run: npm run build
