name: CI

on:
  push: { branches: [ main ] }
  pull_request: { branches: [ main ] }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build (Next.js)
        run: npm run build

      # These two are optional and won’t fail CI if not defined
      - name: Typecheck (optional)
        run: npm run -s typecheck || echo "no typecheck script"

      - name: Lint (optional)
        run: npm run -s lint || echo "no lint script"
